spring:
  application:
    name: replication
  logging:
    level:
      root: info
  datasource:
    url: jdbc:postgresql://localhost:5432/replication
    username: postgres
    password: postgres

replica:
  job:
    name: batch-replica

i18n:
  language: en
